steps:
  # Step 1: Pull the base Python image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'python:3.8-slim']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/atmosphere-palette-app',
      '.'
    ]

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/atmosphere-palette-app'
    ]

 

images:
  - 'gcr.io/$PROJECT_ID/atmosphere-palette-app'
