steps:
  # Step 1: Pull the base Python image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'python:3.8-slim']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/atmosphere-palette-app',
      '.'
    ]

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/atmosphere-palette-app'
    ]

  # Step 4: Deploy the image to Cloud Run (if needed)
  # Uncomment the lines below if you want to deploy to Cloud Run directly
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [
  #     'run', 'deploy', 'atmosphere-palette-app',
  #     '--image', 'gcr.io/$PROJECT_ID/atmosphere-palette-app',
  #     '--platform', 'managed',
  #     '--region', 'us-central1',  # You can change the region as per your needs
  #     '--allow-unauthenticated'  # Optional: allows public access
  #   ]

images:
  - 'gcr.io/$PROJECT_ID/atmosphere-palette-app'

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
