steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-weather-app-dev', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-weather-app-dev']

  # Deploy the image to Cloud Run in the development environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'flask-weather-app-dev',
           '--image', 'gcr.io/$PROJECT_ID/flask-weather-app-dev',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

substitutions:
  _REGION: 'us-central1'
